### PR TITLE
Fix Load more button to work with inherited templates

### PR DESCRIPTION
**Pull request by nickpagz**
This PR attempts to fix the issues mentioned in #5 by conditionally building the button href to match how the core query block uses pagination links for inherited vs non-inherited template queries.

### Testing
- On a sample site with several posts, set a query block to **_not_** inherit the query from the template.
- On the front-end, test by clicking on the "load more" button.
- Additional, different/non-repeating posts should load.
- Now change the query block to "inherit" query from the template.
- Run the same test again. Additional, different/non-repeating posts should once again load.

### CODE REVIEW

**Comment by gin0115** [comment]
```html
<!-- wp:query {"queryId":3,"query":{"perPage":3,"pages":0,"offset":0,"postType":"product","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":true,"parents":[]}} -->
```

When not inherited from template

initial = https://pinkcrab.gq/some-test/

-> Click load more 
Loads 3 more products (correct)
URL = https://pinkcrab.gq/some-test/?query-3-page=2

-> Click load more
Loads 3 more products (corect)
Load more button vanished as only 9 products!
URL = https://pinkcrab.gq/some-test/?query-3-page=3

***********

When inherited from Template

initial = https://pinkcrab.gq/some-test/

-> Click load more 
Loads posts in (5x) but wrong post type! (was product now post)
url now `https://pinkcrab.gq/page/2/`

-> Click load more
Loads no more posts 
button says loading...
404 in dev tools, as it tried to load https://pinkcrab.gq/page/3/

**Comment by nickpagz** [comment]
>When inherited from Template ....

@gin0115 Can you test this again? It's my understanding the "inherited" template will/should always default to posts, unless the theme changes this behaviour. I could be wrong, but on the default themes I've tested, switching to "inherited" always reverted the query back to posts in the original order and no additional filtering. So in your case, loading as posts instead of products is expected afaik, though the 404 is mysterious - I'm not able to replicate this. The loaded url is correct.

**Comment by gin0115** [comment]
hmmm I cant seem to replicate it today, we still get the weird mis match on loops and the URLs for inherited loops are set for the homepage

https://drive.google.com/file/d/1-zimKe3YJy-FPRCfKlz7aFI4TDkfjUnr/view?usp=sharing
(excuse the background noise, school holidays and my son gets excited when i start talking on calls or just in general)

**Comment by nickpagz** [comment]
Ok, thanks for checking Glynn. I think as far as this PR goes, it addresses the issue with the load more button not working correctly on query loops where the query is inherited. I'll go ahead and clean this up, merge, and then deploy it. The issue with the query params and the "[more than one query loop block](https://github.com/a8cteam51/query-loop-load-more/issues/15)" will need to be addressed separately as I think they might be a bit more of a heavy lift.

**Pull request merged**
